/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 75
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_number = 1,
  sym_string = 2,
  sym_word = 3,
  sym_comment = 4,
  anon_sym_if = 5,
  anon_sym_else = 6,
  anon_sym_endif = 7,
  sym_op = 8,
  anon_sym_while = 9,
  anon_sym_do = 10,
  anon_sym_endwhile = 11,
  sym_source_file = 12,
  sym__statement = 13,
  sym_if_statement = 14,
  sym_while_statement = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_word] = "word",
  [sym_comment] = "comment",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [sym_op] = "op",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_endwhile] = "endwhile",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_word] = sym_word,
  [sym_comment] = sym_comment,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [sym_op] = sym_op,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_endwhile] = anon_sym_endwhile,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endwhile] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 4,
  [8] = 2,
  [9] = 4,
  [10] = 2,
  [11] = 4,
  [12] = 2,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 3,
  [20] = 3,
  [21] = 3,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 16,
  [29] = 17,
  [30] = 18,
  [31] = 31,
  [32] = 23,
  [33] = 13,
  [34] = 13,
  [35] = 25,
  [36] = 26,
  [37] = 15,
  [38] = 16,
  [39] = 17,
  [40] = 18,
  [41] = 14,
  [42] = 23,
  [43] = 3,
  [44] = 13,
  [45] = 25,
  [46] = 26,
  [47] = 15,
  [48] = 16,
  [49] = 17,
  [50] = 18,
  [51] = 23,
  [52] = 25,
  [53] = 13,
  [54] = 25,
  [55] = 26,
  [56] = 15,
  [57] = 16,
  [58] = 17,
  [59] = 18,
  [60] = 31,
  [61] = 14,
  [62] = 31,
  [63] = 14,
  [64] = 31,
  [65] = 14,
  [66] = 31,
  [67] = 15,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 70,
  [76] = 71,
  [77] = 71,
  [78] = 72,
  [79] = 73,
  [80] = 74,
  [81] = 68,
  [82] = 69,
  [83] = 74,
  [84] = 71,
  [85] = 71,
  [86] = 70,
  [87] = 72,
  [88] = 73,
  [89] = 74,
  [90] = 68,
  [91] = 68,
  [92] = 72,
  [93] = 68,
  [94] = 69,
  [95] = 73,
  [96] = 74,
  [97] = 72,
  [98] = 69,
  [99] = 70,
  [100] = 73,
  [101] = 69,
  [102] = 70,
  [103] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 5,
        '/', 39,
        'd', 30,
        'e', 24,
        'i', 16,
        'w', 18,
        '%', 38,
        '*', 38,
        '+', 38,
        '-', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 5,
        '/', 39,
        'd', 30,
        'i', 16,
        'w', 18,
        '%', 38,
        '*', 38,
        '+', 38,
        '-', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 5,
        '/', 39,
        'e', 29,
        'i', 16,
        'w', 18,
        '%', 38,
        '*', 38,
        '+', 38,
        '-', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 5,
        '/', 39,
        'e', 25,
        'i', 16,
        'w', 18,
        '%', 38,
        '*', 38,
        '+', 38,
        '-', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 5,
        '/', 39,
        'e', 28,
        'i', 16,
        'w', 18,
        '%', 38,
        '*', 38,
        '+', 38,
        '-', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(9);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'w') ADVANCE(18);
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'f') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'f') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'w') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'n') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 's') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'w') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_endif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_op);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_endwhile);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 6},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 6},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [sym_op] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_endwhile] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(103),
    [sym__statement] = STATE(22),
    [sym_if_statement] = STATE(22),
    [sym_while_statement] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(5),
    [anon_sym_if] = ACTIONS(9),
    [sym_op] = ACTIONS(7),
    [anon_sym_while] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(19),
    [anon_sym_endif] = ACTIONS(21),
    [sym_op] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [sym_word] = ACTIONS(28),
    [sym_comment] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_else] = ACTIONS(34),
    [anon_sym_endif] = ACTIONS(34),
    [sym_op] = ACTIONS(28),
    [anon_sym_while] = ACTIONS(36),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_while_statement] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_word] = ACTIONS(41),
    [sym_comment] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(43),
    [anon_sym_endif] = ACTIONS(45),
    [sym_op] = ACTIONS(41),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(47),
    [anon_sym_endif] = ACTIONS(49),
    [sym_op] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_while_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_number] = ACTIONS(51),
    [sym_string] = ACTIONS(51),
    [sym_word] = ACTIONS(53),
    [sym_comment] = ACTIONS(51),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(55),
    [anon_sym_endif] = ACTIONS(57),
    [sym_op] = ACTIONS(53),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_while_statement] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [sym_word] = ACTIONS(61),
    [sym_comment] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_endif] = ACTIONS(65),
    [sym_op] = ACTIONS(61),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_endif] = ACTIONS(69),
    [sym_op] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(10),
    [sym_if_statement] = STATE(10),
    [sym_while_statement] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_number] = ACTIONS(71),
    [sym_string] = ACTIONS(71),
    [sym_word] = ACTIONS(73),
    [sym_comment] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(75),
    [anon_sym_endif] = ACTIONS(77),
    [sym_op] = ACTIONS(73),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(79),
    [anon_sym_endif] = ACTIONS(81),
    [sym_op] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(11)] = {
    [sym__statement] = STATE(12),
    [sym_if_statement] = STATE(12),
    [sym_while_statement] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_number] = ACTIONS(83),
    [sym_string] = ACTIONS(83),
    [sym_word] = ACTIONS(85),
    [sym_comment] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(87),
    [anon_sym_endif] = ACTIONS(89),
    [sym_op] = ACTIONS(85),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(12)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(91),
    [anon_sym_endif] = ACTIONS(93),
    [sym_op] = ACTIONS(15),
    [anon_sym_while] = ACTIONS(23),
  },
  [STATE(13)] = {
    [sym__statement] = STATE(67),
    [sym_if_statement] = STATE(67),
    [sym_while_statement] = STATE(67),
    [aux_sym_source_file_repeat1] = STATE(67),
    [sym_number] = ACTIONS(95),
    [sym_string] = ACTIONS(95),
    [sym_word] = ACTIONS(97),
    [sym_comment] = ACTIONS(95),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(97),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(103),
  },
  [STATE(14)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(113),
  },
  [STATE(15)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(119),
  },
  [STATE(16)] = {
    [sym__statement] = STATE(18),
    [sym_if_statement] = STATE(18),
    [sym_while_statement] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [sym_number] = ACTIONS(121),
    [sym_string] = ACTIONS(121),
    [sym_word] = ACTIONS(123),
    [sym_comment] = ACTIONS(121),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(123),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(119),
  },
  [STATE(17)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(131),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(18)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(135),
  },
  [STATE(19)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(137),
    [sym_string] = ACTIONS(137),
    [sym_word] = ACTIONS(140),
    [sym_comment] = ACTIONS(137),
    [anon_sym_if] = ACTIONS(143),
    [sym_op] = ACTIONS(140),
    [anon_sym_while] = ACTIONS(146),
    [anon_sym_do] = ACTIONS(34),
  },
  [STATE(20)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(149),
    [sym_string] = ACTIONS(149),
    [sym_word] = ACTIONS(152),
    [sym_comment] = ACTIONS(149),
    [anon_sym_if] = ACTIONS(155),
    [anon_sym_endif] = ACTIONS(34),
    [sym_op] = ACTIONS(152),
    [anon_sym_while] = ACTIONS(158),
  },
  [STATE(21)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(161),
    [sym_string] = ACTIONS(161),
    [sym_word] = ACTIONS(164),
    [sym_comment] = ACTIONS(161),
    [anon_sym_if] = ACTIONS(167),
    [sym_op] = ACTIONS(164),
    [anon_sym_while] = ACTIONS(170),
    [anon_sym_endwhile] = ACTIONS(34),
  },
  [STATE(22)] = {
    [sym__statement] = STATE(43),
    [sym_if_statement] = STATE(43),
    [sym_while_statement] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(173),
    [sym_number] = ACTIONS(175),
    [sym_string] = ACTIONS(175),
    [sym_word] = ACTIONS(177),
    [sym_comment] = ACTIONS(175),
    [anon_sym_if] = ACTIONS(9),
    [sym_op] = ACTIONS(177),
    [anon_sym_while] = ACTIONS(11),
  },
  [STATE(23)] = {
    [sym__statement] = STATE(25),
    [sym_if_statement] = STATE(25),
    [sym_while_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(25),
    [sym_number] = ACTIONS(179),
    [sym_string] = ACTIONS(179),
    [sym_word] = ACTIONS(181),
    [sym_comment] = ACTIONS(179),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(49),
    [sym_op] = ACTIONS(181),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(24)] = {
    [sym__statement] = STATE(52),
    [sym_if_statement] = STATE(52),
    [sym_while_statement] = STATE(52),
    [aux_sym_source_file_repeat1] = STATE(52),
    [sym_number] = ACTIONS(183),
    [sym_string] = ACTIONS(183),
    [sym_word] = ACTIONS(185),
    [sym_comment] = ACTIONS(183),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(21),
    [sym_op] = ACTIONS(185),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(25)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(187),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(26)] = {
    [sym__statement] = STATE(29),
    [sym_if_statement] = STATE(29),
    [sym_while_statement] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(29),
    [sym_number] = ACTIONS(189),
    [sym_string] = ACTIONS(189),
    [sym_word] = ACTIONS(191),
    [sym_comment] = ACTIONS(189),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(187),
    [sym_op] = ACTIONS(191),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(27)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(193),
    [sym_string] = ACTIONS(193),
    [sym_word] = ACTIONS(195),
    [sym_comment] = ACTIONS(193),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(197),
    [sym_op] = ACTIONS(195),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(28)] = {
    [sym__statement] = STATE(30),
    [sym_if_statement] = STATE(30),
    [sym_while_statement] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(30),
    [sym_number] = ACTIONS(199),
    [sym_string] = ACTIONS(199),
    [sym_word] = ACTIONS(201),
    [sym_comment] = ACTIONS(199),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(201),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(203),
  },
  [STATE(29)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(205),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(30)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(207),
  },
  [STATE(31)] = {
    [sym__statement] = STATE(41),
    [sym_if_statement] = STATE(41),
    [sym_while_statement] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(41),
    [sym_number] = ACTIONS(209),
    [sym_string] = ACTIONS(209),
    [sym_word] = ACTIONS(211),
    [sym_comment] = ACTIONS(209),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(211),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(213),
  },
  [STATE(32)] = {
    [sym__statement] = STATE(35),
    [sym_if_statement] = STATE(35),
    [sym_while_statement] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(35),
    [sym_number] = ACTIONS(215),
    [sym_string] = ACTIONS(215),
    [sym_word] = ACTIONS(217),
    [sym_comment] = ACTIONS(215),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(69),
    [sym_op] = ACTIONS(217),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(33)] = {
    [sym__statement] = STATE(15),
    [sym_if_statement] = STATE(15),
    [sym_while_statement] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [sym_number] = ACTIONS(219),
    [sym_string] = ACTIONS(219),
    [sym_word] = ACTIONS(221),
    [sym_comment] = ACTIONS(219),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(221),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(223),
  },
  [STATE(34)] = {
    [sym__statement] = STATE(37),
    [sym_if_statement] = STATE(37),
    [sym_while_statement] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(37),
    [sym_number] = ACTIONS(225),
    [sym_string] = ACTIONS(225),
    [sym_word] = ACTIONS(227),
    [sym_comment] = ACTIONS(225),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(227),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(229),
  },
  [STATE(35)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(231),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(36)] = {
    [sym__statement] = STATE(39),
    [sym_if_statement] = STATE(39),
    [sym_while_statement] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(39),
    [sym_number] = ACTIONS(233),
    [sym_string] = ACTIONS(233),
    [sym_word] = ACTIONS(235),
    [sym_comment] = ACTIONS(233),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(231),
    [sym_op] = ACTIONS(235),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(37)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(237),
  },
  [STATE(38)] = {
    [sym__statement] = STATE(40),
    [sym_if_statement] = STATE(40),
    [sym_while_statement] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(40),
    [sym_number] = ACTIONS(239),
    [sym_string] = ACTIONS(239),
    [sym_word] = ACTIONS(241),
    [sym_comment] = ACTIONS(239),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(241),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(237),
  },
  [STATE(39)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(243),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(40)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(245),
  },
  [STATE(41)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(247),
  },
  [STATE(42)] = {
    [sym__statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym_while_statement] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [sym_number] = ACTIONS(249),
    [sym_string] = ACTIONS(249),
    [sym_word] = ACTIONS(251),
    [sym_comment] = ACTIONS(249),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(81),
    [sym_op] = ACTIONS(251),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(43)] = {
    [sym__statement] = STATE(43),
    [sym_if_statement] = STATE(43),
    [sym_while_statement] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(253),
    [sym_number] = ACTIONS(255),
    [sym_string] = ACTIONS(255),
    [sym_word] = ACTIONS(258),
    [sym_comment] = ACTIONS(255),
    [anon_sym_if] = ACTIONS(261),
    [sym_op] = ACTIONS(258),
    [anon_sym_while] = ACTIONS(264),
  },
  [STATE(44)] = {
    [sym__statement] = STATE(47),
    [sym_if_statement] = STATE(47),
    [sym_while_statement] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(47),
    [sym_number] = ACTIONS(267),
    [sym_string] = ACTIONS(267),
    [sym_word] = ACTIONS(269),
    [sym_comment] = ACTIONS(267),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(269),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(271),
  },
  [STATE(45)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(273),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(46)] = {
    [sym__statement] = STATE(49),
    [sym_if_statement] = STATE(49),
    [sym_while_statement] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(49),
    [sym_number] = ACTIONS(275),
    [sym_string] = ACTIONS(275),
    [sym_word] = ACTIONS(277),
    [sym_comment] = ACTIONS(275),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(273),
    [sym_op] = ACTIONS(277),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(47)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(279),
  },
  [STATE(48)] = {
    [sym__statement] = STATE(50),
    [sym_if_statement] = STATE(50),
    [sym_while_statement] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(50),
    [sym_number] = ACTIONS(281),
    [sym_string] = ACTIONS(281),
    [sym_word] = ACTIONS(283),
    [sym_comment] = ACTIONS(281),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(283),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(279),
  },
  [STATE(49)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(285),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(50)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(287),
  },
  [STATE(51)] = {
    [sym__statement] = STATE(54),
    [sym_if_statement] = STATE(54),
    [sym_while_statement] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(54),
    [sym_number] = ACTIONS(289),
    [sym_string] = ACTIONS(289),
    [sym_word] = ACTIONS(291),
    [sym_comment] = ACTIONS(289),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(93),
    [sym_op] = ACTIONS(291),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(52)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(197),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(53)] = {
    [sym__statement] = STATE(56),
    [sym_if_statement] = STATE(56),
    [sym_while_statement] = STATE(56),
    [aux_sym_source_file_repeat1] = STATE(56),
    [sym_number] = ACTIONS(293),
    [sym_string] = ACTIONS(293),
    [sym_word] = ACTIONS(295),
    [sym_comment] = ACTIONS(293),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(295),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(297),
  },
  [STATE(54)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(299),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(55)] = {
    [sym__statement] = STATE(58),
    [sym_if_statement] = STATE(58),
    [sym_while_statement] = STATE(58),
    [aux_sym_source_file_repeat1] = STATE(58),
    [sym_number] = ACTIONS(301),
    [sym_string] = ACTIONS(301),
    [sym_word] = ACTIONS(303),
    [sym_comment] = ACTIONS(301),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(299),
    [sym_op] = ACTIONS(303),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(56)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(305),
  },
  [STATE(57)] = {
    [sym__statement] = STATE(59),
    [sym_if_statement] = STATE(59),
    [sym_while_statement] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(59),
    [sym_number] = ACTIONS(307),
    [sym_string] = ACTIONS(307),
    [sym_word] = ACTIONS(309),
    [sym_comment] = ACTIONS(307),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(309),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(305),
  },
  [STATE(58)] = {
    [sym__statement] = STATE(20),
    [sym_if_statement] = STATE(20),
    [sym_while_statement] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(20),
    [sym_number] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [sym_word] = ACTIONS(127),
    [sym_comment] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_endif] = ACTIONS(311),
    [sym_op] = ACTIONS(127),
    [anon_sym_while] = ACTIONS(133),
  },
  [STATE(59)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(313),
  },
  [STATE(60)] = {
    [sym__statement] = STATE(61),
    [sym_if_statement] = STATE(61),
    [sym_while_statement] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(61),
    [sym_number] = ACTIONS(315),
    [sym_string] = ACTIONS(315),
    [sym_word] = ACTIONS(317),
    [sym_comment] = ACTIONS(315),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(317),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(319),
  },
  [STATE(61)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(321),
  },
  [STATE(62)] = {
    [sym__statement] = STATE(63),
    [sym_if_statement] = STATE(63),
    [sym_while_statement] = STATE(63),
    [aux_sym_source_file_repeat1] = STATE(63),
    [sym_number] = ACTIONS(323),
    [sym_string] = ACTIONS(323),
    [sym_word] = ACTIONS(325),
    [sym_comment] = ACTIONS(323),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(325),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(327),
  },
  [STATE(63)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(329),
  },
  [STATE(64)] = {
    [sym__statement] = STATE(65),
    [sym_if_statement] = STATE(65),
    [sym_while_statement] = STATE(65),
    [aux_sym_source_file_repeat1] = STATE(65),
    [sym_number] = ACTIONS(331),
    [sym_string] = ACTIONS(331),
    [sym_word] = ACTIONS(333),
    [sym_comment] = ACTIONS(331),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(333),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(335),
  },
  [STATE(65)] = {
    [sym__statement] = STATE(19),
    [sym_if_statement] = STATE(19),
    [sym_while_statement] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_comment] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(107),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(337),
  },
  [STATE(66)] = {
    [sym__statement] = STATE(14),
    [sym_if_statement] = STATE(14),
    [sym_while_statement] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [sym_number] = ACTIONS(339),
    [sym_string] = ACTIONS(339),
    [sym_word] = ACTIONS(341),
    [sym_comment] = ACTIONS(339),
    [anon_sym_if] = ACTIONS(109),
    [sym_op] = ACTIONS(341),
    [anon_sym_while] = ACTIONS(111),
    [anon_sym_do] = ACTIONS(343),
  },
  [STATE(67)] = {
    [sym__statement] = STATE(21),
    [sym_if_statement] = STATE(21),
    [sym_while_statement] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(99),
    [sym_op] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_endwhile] = ACTIONS(203),
  },
  [STATE(68)] = {
    [sym_number] = ACTIONS(345),
    [sym_string] = ACTIONS(345),
    [sym_word] = ACTIONS(347),
    [sym_comment] = ACTIONS(345),
    [anon_sym_if] = ACTIONS(347),
    [anon_sym_else] = ACTIONS(347),
    [anon_sym_endif] = ACTIONS(347),
    [sym_op] = ACTIONS(347),
    [anon_sym_while] = ACTIONS(347),
  },
  [STATE(69)] = {
    [sym_number] = ACTIONS(349),
    [sym_string] = ACTIONS(349),
    [sym_word] = ACTIONS(351),
    [sym_comment] = ACTIONS(349),
    [anon_sym_if] = ACTIONS(351),
    [anon_sym_else] = ACTIONS(351),
    [anon_sym_endif] = ACTIONS(351),
    [sym_op] = ACTIONS(351),
    [anon_sym_while] = ACTIONS(351),
  },
  [STATE(70)] = {
    [sym_number] = ACTIONS(353),
    [sym_string] = ACTIONS(353),
    [sym_word] = ACTIONS(355),
    [sym_comment] = ACTIONS(353),
    [anon_sym_if] = ACTIONS(355),
    [anon_sym_else] = ACTIONS(355),
    [anon_sym_endif] = ACTIONS(355),
    [sym_op] = ACTIONS(355),
    [anon_sym_while] = ACTIONS(355),
  },
  [STATE(71)] = {
    [sym_number] = ACTIONS(357),
    [sym_string] = ACTIONS(357),
    [sym_word] = ACTIONS(359),
    [sym_comment] = ACTIONS(357),
    [anon_sym_if] = ACTIONS(359),
    [anon_sym_else] = ACTIONS(359),
    [anon_sym_endif] = ACTIONS(359),
    [sym_op] = ACTIONS(359),
    [anon_sym_while] = ACTIONS(359),
  },
  [STATE(72)] = {
    [sym_number] = ACTIONS(361),
    [sym_string] = ACTIONS(361),
    [sym_word] = ACTIONS(363),
    [sym_comment] = ACTIONS(361),
    [anon_sym_if] = ACTIONS(363),
    [anon_sym_else] = ACTIONS(363),
    [anon_sym_endif] = ACTIONS(363),
    [sym_op] = ACTIONS(363),
    [anon_sym_while] = ACTIONS(363),
  },
  [STATE(73)] = {
    [sym_number] = ACTIONS(365),
    [sym_string] = ACTIONS(365),
    [sym_word] = ACTIONS(367),
    [sym_comment] = ACTIONS(365),
    [anon_sym_if] = ACTIONS(367),
    [anon_sym_else] = ACTIONS(367),
    [anon_sym_endif] = ACTIONS(367),
    [sym_op] = ACTIONS(367),
    [anon_sym_while] = ACTIONS(367),
  },
  [STATE(74)] = {
    [sym_number] = ACTIONS(369),
    [sym_string] = ACTIONS(369),
    [sym_word] = ACTIONS(371),
    [sym_comment] = ACTIONS(369),
    [anon_sym_if] = ACTIONS(371),
    [anon_sym_else] = ACTIONS(371),
    [anon_sym_endif] = ACTIONS(371),
    [sym_op] = ACTIONS(371),
    [anon_sym_while] = ACTIONS(371),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(353), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(355), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [13] = 2,
    ACTIONS(357), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(359), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [26] = 2,
    ACTIONS(357), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(359), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [39] = 2,
    ACTIONS(361), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(363), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [52] = 2,
    ACTIONS(365), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(367), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [65] = 2,
    ACTIONS(369), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(371), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [78] = 2,
    ACTIONS(345), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(347), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [91] = 2,
    ACTIONS(349), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(351), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [104] = 2,
    ACTIONS(369), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(371), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [117] = 2,
    ACTIONS(357), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(359), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [130] = 2,
    ACTIONS(357), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(359), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [143] = 2,
    ACTIONS(353), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(355), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [156] = 2,
    ACTIONS(361), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(363), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [169] = 2,
    ACTIONS(365), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(367), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [182] = 2,
    ACTIONS(369), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(371), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [195] = 2,
    ACTIONS(345), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(347), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_endwhile,
  [208] = 2,
    ACTIONS(345), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(347), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [221] = 2,
    ACTIONS(361), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(363), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [234] = 2,
    ACTIONS(345), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(347), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [247] = 2,
    ACTIONS(349), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(351), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [260] = 2,
    ACTIONS(365), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(367), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [273] = 2,
    ACTIONS(369), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(371), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [286] = 2,
    ACTIONS(361), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(363), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [299] = 2,
    ACTIONS(349), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(351), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [312] = 2,
    ACTIONS(353), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(355), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      sym_op,
      anon_sym_while,
  [325] = 2,
    ACTIONS(365), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(367), 4,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
  [338] = 2,
    ACTIONS(349), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(351), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [351] = 2,
    ACTIONS(353), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(355), 5,
      sym_word,
      anon_sym_if,
      sym_op,
      anon_sym_while,
      anon_sym_do,
  [364] = 1,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(75)] = 0,
  [SMALL_STATE(76)] = 13,
  [SMALL_STATE(77)] = 26,
  [SMALL_STATE(78)] = 39,
  [SMALL_STATE(79)] = 52,
  [SMALL_STATE(80)] = 65,
  [SMALL_STATE(81)] = 78,
  [SMALL_STATE(82)] = 91,
  [SMALL_STATE(83)] = 104,
  [SMALL_STATE(84)] = 117,
  [SMALL_STATE(85)] = 130,
  [SMALL_STATE(86)] = 143,
  [SMALL_STATE(87)] = 156,
  [SMALL_STATE(88)] = 169,
  [SMALL_STATE(89)] = 182,
  [SMALL_STATE(90)] = 195,
  [SMALL_STATE(91)] = 208,
  [SMALL_STATE(92)] = 221,
  [SMALL_STATE(93)] = 234,
  [SMALL_STATE(94)] = 247,
  [SMALL_STATE(95)] = 260,
  [SMALL_STATE(96)] = 273,
  [SMALL_STATE(97)] = 286,
  [SMALL_STATE(98)] = 299,
  [SMALL_STATE(99)] = 312,
  [SMALL_STATE(100)] = 325,
  [SMALL_STATE(101)] = 338,
  [SMALL_STATE(102)] = 351,
  [SMALL_STATE(103)] = 364,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [258] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [264] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [337] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [343] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 5, 0, 0),
  [347] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 5, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, 0, 0),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 4, 0, 0),
  [367] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 4, 0, 0),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [371] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [373] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_platypus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "platypus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
