/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 55
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_number = 1,
  sym_string = 2,
  sym_word = 3,
  sym_comment = 4,
  anon_sym_if = 5,
  anon_sym_else = 6,
  anon_sym_endif = 7,
  anon_sym_while = 8,
  anon_sym_endwhile = 9,
  anon_sym_do = 10,
  sym_source_file = 11,
  sym__statement = 12,
  sym_if_statement = 13,
  sym_while_statement = 14,
  sym_do_statement = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_word] = "word",
  [sym_comment] = "comment",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [anon_sym_while] = "while",
  [anon_sym_endwhile] = "endwhile",
  [anon_sym_do] = "do",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_do_statement] = "do_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_word] = sym_word,
  [sym_comment] = sym_comment,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_endwhile] = anon_sym_endwhile,
  [anon_sym_do] = anon_sym_do,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_do_statement] = sym_do_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endwhile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_do_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 2,
  [8] = 3,
  [9] = 2,
  [10] = 3,
  [11] = 11,
  [12] = 12,
  [13] = 4,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 4,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 11,
  [22] = 19,
  [23] = 23,
  [24] = 12,
  [25] = 14,
  [26] = 15,
  [27] = 16,
  [28] = 19,
  [29] = 20,
  [30] = 11,
  [31] = 20,
  [32] = 23,
  [33] = 12,
  [34] = 14,
  [35] = 15,
  [36] = 16,
  [37] = 19,
  [38] = 20,
  [39] = 11,
  [40] = 23,
  [41] = 23,
  [42] = 12,
  [43] = 14,
  [44] = 15,
  [45] = 16,
  [46] = 4,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 49,
  [56] = 54,
  [57] = 54,
  [58] = 51,
  [59] = 47,
  [60] = 48,
  [61] = 47,
  [62] = 53,
  [63] = 48,
  [64] = 49,
  [65] = 50,
  [66] = 52,
  [67] = 51,
  [68] = 52,
  [69] = 49,
  [70] = 53,
  [71] = 54,
  [72] = 47,
  [73] = 48,
  [74] = 53,
  [75] = 50,
  [76] = 50,
  [77] = 51,
  [78] = 52,
  [79] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'd') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'f') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'f') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'w') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'n') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 's') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'w') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_endif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_endwhile);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_endwhile] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(79),
    [sym__statement] = STATE(18),
    [sym_if_statement] = STATE(18),
    [sym_while_statement] = STATE(18),
    [sym_do_statement] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(5),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_do] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [sym_do_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_number] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
    [sym_comment] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(21),
    [anon_sym_endif] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_do_statement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_word] = ACTIONS(31),
    [sym_comment] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(33),
    [anon_sym_endif] = ACTIONS(35),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_do_statement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_number] = ACTIONS(37),
    [sym_string] = ACTIONS(37),
    [sym_word] = ACTIONS(40),
    [sym_comment] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(43),
    [anon_sym_else] = ACTIONS(46),
    [anon_sym_endif] = ACTIONS(46),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_do] = ACTIONS(51),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_do_statement] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_number] = ACTIONS(54),
    [sym_string] = ACTIONS(54),
    [sym_word] = ACTIONS(56),
    [sym_comment] = ACTIONS(54),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(58),
    [anon_sym_endif] = ACTIONS(60),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_do_statement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_word] = ACTIONS(31),
    [sym_comment] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(62),
    [anon_sym_endif] = ACTIONS(64),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_while_statement] = STATE(8),
    [sym_do_statement] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_number] = ACTIONS(66),
    [sym_string] = ACTIONS(66),
    [sym_word] = ACTIONS(68),
    [sym_comment] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(70),
    [anon_sym_endif] = ACTIONS(72),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_do_statement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_word] = ACTIONS(31),
    [sym_comment] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_endif] = ACTIONS(76),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(10),
    [sym_if_statement] = STATE(10),
    [sym_while_statement] = STATE(10),
    [sym_do_statement] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_number] = ACTIONS(78),
    [sym_string] = ACTIONS(78),
    [sym_word] = ACTIONS(80),
    [sym_comment] = ACTIONS(78),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(82),
    [anon_sym_endif] = ACTIONS(84),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_do_statement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_word] = ACTIONS(31),
    [sym_comment] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(86),
    [anon_sym_endif] = ACTIONS(88),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_do] = ACTIONS(27),
  },
  [STATE(11)] = {
    [sym__statement] = STATE(14),
    [sym_if_statement] = STATE(14),
    [sym_while_statement] = STATE(14),
    [sym_do_statement] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [sym_number] = ACTIONS(90),
    [sym_string] = ACTIONS(90),
    [sym_word] = ACTIONS(92),
    [sym_comment] = ACTIONS(90),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(35),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(12)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(108),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(13)] = {
    [sym__statement] = STATE(13),
    [sym_if_statement] = STATE(13),
    [sym_while_statement] = STATE(13),
    [sym_do_statement] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_number] = ACTIONS(114),
    [sym_string] = ACTIONS(114),
    [sym_word] = ACTIONS(117),
    [sym_comment] = ACTIONS(114),
    [anon_sym_if] = ACTIONS(120),
    [anon_sym_while] = ACTIONS(123),
    [anon_sym_do] = ACTIONS(126),
  },
  [STATE(14)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(133),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(15)] = {
    [sym__statement] = STATE(16),
    [sym_if_statement] = STATE(16),
    [sym_while_statement] = STATE(16),
    [sym_do_statement] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_number] = ACTIONS(135),
    [sym_string] = ACTIONS(135),
    [sym_word] = ACTIONS(137),
    [sym_comment] = ACTIONS(135),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(133),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(16)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(139),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(17)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(141),
    [sym_string] = ACTIONS(141),
    [sym_word] = ACTIONS(144),
    [sym_comment] = ACTIONS(141),
    [anon_sym_if] = ACTIONS(147),
    [anon_sym_while] = ACTIONS(150),
    [anon_sym_endwhile] = ACTIONS(46),
    [anon_sym_do] = ACTIONS(153),
  },
  [STATE(18)] = {
    [sym__statement] = STATE(13),
    [sym_if_statement] = STATE(13),
    [sym_while_statement] = STATE(13),
    [sym_do_statement] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(156),
    [sym_number] = ACTIONS(158),
    [sym_string] = ACTIONS(158),
    [sym_word] = ACTIONS(160),
    [sym_comment] = ACTIONS(158),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_do] = ACTIONS(13),
  },
  [STATE(19)] = {
    [sym__statement] = STATE(23),
    [sym_if_statement] = STATE(23),
    [sym_while_statement] = STATE(23),
    [sym_do_statement] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(23),
    [sym_number] = ACTIONS(162),
    [sym_string] = ACTIONS(162),
    [sym_word] = ACTIONS(164),
    [sym_comment] = ACTIONS(162),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(166),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(20)] = {
    [sym__statement] = STATE(24),
    [sym_if_statement] = STATE(24),
    [sym_while_statement] = STATE(24),
    [sym_do_statement] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(24),
    [sym_number] = ACTIONS(168),
    [sym_string] = ACTIONS(168),
    [sym_word] = ACTIONS(170),
    [sym_comment] = ACTIONS(168),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(172),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(21)] = {
    [sym__statement] = STATE(25),
    [sym_if_statement] = STATE(25),
    [sym_while_statement] = STATE(25),
    [sym_do_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(25),
    [sym_number] = ACTIONS(174),
    [sym_string] = ACTIONS(174),
    [sym_word] = ACTIONS(176),
    [sym_comment] = ACTIONS(174),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(64),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(22)] = {
    [sym__statement] = STATE(40),
    [sym_if_statement] = STATE(40),
    [sym_while_statement] = STATE(40),
    [sym_do_statement] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(40),
    [sym_number] = ACTIONS(178),
    [sym_string] = ACTIONS(178),
    [sym_word] = ACTIONS(180),
    [sym_comment] = ACTIONS(178),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(182),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(23)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(184),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(24)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(186),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(25)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(188),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(26)] = {
    [sym__statement] = STATE(27),
    [sym_if_statement] = STATE(27),
    [sym_while_statement] = STATE(27),
    [sym_do_statement] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(27),
    [sym_number] = ACTIONS(190),
    [sym_string] = ACTIONS(190),
    [sym_word] = ACTIONS(192),
    [sym_comment] = ACTIONS(190),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(188),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(27)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(194),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(28)] = {
    [sym__statement] = STATE(32),
    [sym_if_statement] = STATE(32),
    [sym_while_statement] = STATE(32),
    [sym_do_statement] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [sym_number] = ACTIONS(196),
    [sym_string] = ACTIONS(196),
    [sym_word] = ACTIONS(198),
    [sym_comment] = ACTIONS(196),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(200),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(29)] = {
    [sym__statement] = STATE(33),
    [sym_if_statement] = STATE(33),
    [sym_while_statement] = STATE(33),
    [sym_do_statement] = STATE(33),
    [aux_sym_source_file_repeat1] = STATE(33),
    [sym_number] = ACTIONS(202),
    [sym_string] = ACTIONS(202),
    [sym_word] = ACTIONS(204),
    [sym_comment] = ACTIONS(202),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(206),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(30)] = {
    [sym__statement] = STATE(34),
    [sym_if_statement] = STATE(34),
    [sym_while_statement] = STATE(34),
    [sym_do_statement] = STATE(34),
    [aux_sym_source_file_repeat1] = STATE(34),
    [sym_number] = ACTIONS(208),
    [sym_string] = ACTIONS(208),
    [sym_word] = ACTIONS(210),
    [sym_comment] = ACTIONS(208),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(76),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(31)] = {
    [sym__statement] = STATE(12),
    [sym_if_statement] = STATE(12),
    [sym_while_statement] = STATE(12),
    [sym_do_statement] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_number] = ACTIONS(212),
    [sym_string] = ACTIONS(212),
    [sym_word] = ACTIONS(214),
    [sym_comment] = ACTIONS(212),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(216),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(32)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(218),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(33)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(220),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(34)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(222),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(35)] = {
    [sym__statement] = STATE(36),
    [sym_if_statement] = STATE(36),
    [sym_while_statement] = STATE(36),
    [sym_do_statement] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(36),
    [sym_number] = ACTIONS(224),
    [sym_string] = ACTIONS(224),
    [sym_word] = ACTIONS(226),
    [sym_comment] = ACTIONS(224),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(222),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(36)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(228),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(37)] = {
    [sym__statement] = STATE(41),
    [sym_if_statement] = STATE(41),
    [sym_while_statement] = STATE(41),
    [sym_do_statement] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(41),
    [sym_number] = ACTIONS(230),
    [sym_string] = ACTIONS(230),
    [sym_word] = ACTIONS(232),
    [sym_comment] = ACTIONS(230),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(234),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(38)] = {
    [sym__statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym_while_statement] = STATE(42),
    [sym_do_statement] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(42),
    [sym_number] = ACTIONS(236),
    [sym_string] = ACTIONS(236),
    [sym_word] = ACTIONS(238),
    [sym_comment] = ACTIONS(236),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(240),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(39)] = {
    [sym__statement] = STATE(43),
    [sym_if_statement] = STATE(43),
    [sym_while_statement] = STATE(43),
    [sym_do_statement] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(43),
    [sym_number] = ACTIONS(242),
    [sym_string] = ACTIONS(242),
    [sym_word] = ACTIONS(244),
    [sym_comment] = ACTIONS(242),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(88),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(40)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(246),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(41)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(248),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(42)] = {
    [sym__statement] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_while_statement] = STATE(17),
    [sym_do_statement] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_number] = ACTIONS(100),
    [sym_string] = ACTIONS(100),
    [sym_word] = ACTIONS(102),
    [sym_comment] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_endwhile] = ACTIONS(250),
    [anon_sym_do] = ACTIONS(110),
  },
  [STATE(43)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(252),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(44)] = {
    [sym__statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym_while_statement] = STATE(45),
    [sym_do_statement] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [sym_number] = ACTIONS(254),
    [sym_string] = ACTIONS(254),
    [sym_word] = ACTIONS(256),
    [sym_comment] = ACTIONS(254),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(252),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(45)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(129),
    [sym_string] = ACTIONS(129),
    [sym_word] = ACTIONS(131),
    [sym_comment] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_endif] = ACTIONS(258),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(98),
  },
  [STATE(46)] = {
    [sym__statement] = STATE(46),
    [sym_if_statement] = STATE(46),
    [sym_while_statement] = STATE(46),
    [sym_do_statement] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(46),
    [sym_number] = ACTIONS(260),
    [sym_string] = ACTIONS(260),
    [sym_word] = ACTIONS(263),
    [sym_comment] = ACTIONS(260),
    [anon_sym_if] = ACTIONS(266),
    [anon_sym_endif] = ACTIONS(46),
    [anon_sym_while] = ACTIONS(269),
    [anon_sym_do] = ACTIONS(272),
  },
  [STATE(47)] = {
    [sym_number] = ACTIONS(275),
    [sym_string] = ACTIONS(275),
    [sym_word] = ACTIONS(277),
    [sym_comment] = ACTIONS(275),
    [anon_sym_if] = ACTIONS(277),
    [anon_sym_else] = ACTIONS(277),
    [anon_sym_endif] = ACTIONS(277),
    [anon_sym_while] = ACTIONS(277),
    [anon_sym_do] = ACTIONS(277),
  },
  [STATE(48)] = {
    [sym_number] = ACTIONS(279),
    [sym_string] = ACTIONS(279),
    [sym_word] = ACTIONS(281),
    [sym_comment] = ACTIONS(279),
    [anon_sym_if] = ACTIONS(281),
    [anon_sym_else] = ACTIONS(281),
    [anon_sym_endif] = ACTIONS(281),
    [anon_sym_while] = ACTIONS(281),
    [anon_sym_do] = ACTIONS(281),
  },
  [STATE(49)] = {
    [sym_number] = ACTIONS(283),
    [sym_string] = ACTIONS(283),
    [sym_word] = ACTIONS(285),
    [sym_comment] = ACTIONS(283),
    [anon_sym_if] = ACTIONS(285),
    [anon_sym_else] = ACTIONS(285),
    [anon_sym_endif] = ACTIONS(285),
    [anon_sym_while] = ACTIONS(285),
    [anon_sym_do] = ACTIONS(285),
  },
  [STATE(50)] = {
    [sym_number] = ACTIONS(287),
    [sym_string] = ACTIONS(287),
    [sym_word] = ACTIONS(289),
    [sym_comment] = ACTIONS(287),
    [anon_sym_if] = ACTIONS(289),
    [anon_sym_else] = ACTIONS(289),
    [anon_sym_endif] = ACTIONS(289),
    [anon_sym_while] = ACTIONS(289),
    [anon_sym_do] = ACTIONS(289),
  },
  [STATE(51)] = {
    [sym_number] = ACTIONS(291),
    [sym_string] = ACTIONS(291),
    [sym_word] = ACTIONS(293),
    [sym_comment] = ACTIONS(291),
    [anon_sym_if] = ACTIONS(293),
    [anon_sym_else] = ACTIONS(293),
    [anon_sym_endif] = ACTIONS(293),
    [anon_sym_while] = ACTIONS(293),
    [anon_sym_do] = ACTIONS(293),
  },
  [STATE(52)] = {
    [sym_number] = ACTIONS(295),
    [sym_string] = ACTIONS(295),
    [sym_word] = ACTIONS(297),
    [sym_comment] = ACTIONS(295),
    [anon_sym_if] = ACTIONS(297),
    [anon_sym_else] = ACTIONS(297),
    [anon_sym_endif] = ACTIONS(297),
    [anon_sym_while] = ACTIONS(297),
    [anon_sym_do] = ACTIONS(297),
  },
  [STATE(53)] = {
    [sym_number] = ACTIONS(299),
    [sym_string] = ACTIONS(299),
    [sym_word] = ACTIONS(301),
    [sym_comment] = ACTIONS(299),
    [anon_sym_if] = ACTIONS(301),
    [anon_sym_else] = ACTIONS(301),
    [anon_sym_endif] = ACTIONS(301),
    [anon_sym_while] = ACTIONS(301),
    [anon_sym_do] = ACTIONS(301),
  },
  [STATE(54)] = {
    [sym_number] = ACTIONS(303),
    [sym_string] = ACTIONS(303),
    [sym_word] = ACTIONS(305),
    [sym_comment] = ACTIONS(303),
    [anon_sym_if] = ACTIONS(305),
    [anon_sym_else] = ACTIONS(305),
    [anon_sym_endif] = ACTIONS(305),
    [anon_sym_while] = ACTIONS(305),
    [anon_sym_do] = ACTIONS(305),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(283), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(285), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [13] = 2,
    ACTIONS(303), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(305), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [26] = 2,
    ACTIONS(303), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(305), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [39] = 2,
    ACTIONS(291), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(293), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [52] = 2,
    ACTIONS(275), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(277), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [65] = 2,
    ACTIONS(279), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(281), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [78] = 2,
    ACTIONS(275), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(277), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [91] = 2,
    ACTIONS(299), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(301), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [104] = 2,
    ACTIONS(279), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(281), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [117] = 2,
    ACTIONS(283), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(285), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [130] = 2,
    ACTIONS(287), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(289), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [143] = 2,
    ACTIONS(295), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(297), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [156] = 2,
    ACTIONS(291), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(293), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [169] = 2,
    ACTIONS(295), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(297), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [182] = 2,
    ACTIONS(283), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(285), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [195] = 2,
    ACTIONS(299), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(301), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [208] = 2,
    ACTIONS(303), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(305), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [221] = 2,
    ACTIONS(275), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(277), 5,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_do,
  [234] = 2,
    ACTIONS(279), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(281), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [247] = 2,
    ACTIONS(299), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(301), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [260] = 2,
    ACTIONS(287), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(289), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [273] = 2,
    ACTIONS(287), 4,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(289), 4,
      sym_word,
      anon_sym_if,
      anon_sym_while,
      anon_sym_do,
  [286] = 2,
    ACTIONS(291), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(293), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [299] = 2,
    ACTIONS(295), 3,
      sym_number,
      sym_string,
      sym_comment,
    ACTIONS(297), 5,
      sym_word,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_while,
      anon_sym_do,
  [312] = 1,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(55)] = 0,
  [SMALL_STATE(56)] = 13,
  [SMALL_STATE(57)] = 26,
  [SMALL_STATE(58)] = 39,
  [SMALL_STATE(59)] = 52,
  [SMALL_STATE(60)] = 65,
  [SMALL_STATE(61)] = 78,
  [SMALL_STATE(62)] = 91,
  [SMALL_STATE(63)] = 104,
  [SMALL_STATE(64)] = 117,
  [SMALL_STATE(65)] = 130,
  [SMALL_STATE(66)] = 143,
  [SMALL_STATE(67)] = 156,
  [SMALL_STATE(68)] = 169,
  [SMALL_STATE(69)] = 182,
  [SMALL_STATE(70)] = 195,
  [SMALL_STATE(71)] = 208,
  [SMALL_STATE(72)] = 221,
  [SMALL_STATE(73)] = 234,
  [SMALL_STATE(74)] = 247,
  [SMALL_STATE(75)] = 260,
  [SMALL_STATE(76)] = 273,
  [SMALL_STATE(77)] = 286,
  [SMALL_STATE(78)] = 299,
  [SMALL_STATE(79)] = 312,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [263] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [266] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_statement, 2, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_statement, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_statement, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_statement, 3, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_platypus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
